system_parameters = {
    "min_withdrawal_batch_size": 8,
    "max_withdrawal_batch_size": 128,
    "first_seal_rage_quit_support": 3,
    "second_seal_rage_quit_support": 15,
    "dynamic_timelock_min_duration": 5,
    "dynamic_timelock_max_duration": 45,
    "veto_signalling_min_active_duration": 5,
    "veto_signalling_deactivation_max_duration": 3,
    "veto_cooldown_duration": 5,
    "rage_quit_extension_delay": 7,
    "rage_quit_eth_withdrawals_min_timelock": 60,
    "rage_quit_eth_withdrawals_max_timelock": 180,
    "rage_quit_eth_withdrawals_delay_growth": 15,
    "tie_break_activation_timeout": 365,
}
